### ISSUE TITLE
실행 에러

### ISSUE THREAD

**Issue by jeonghoonkang** [wonch01/data_to_db#2]
아래와 같은 에러가 발생 합니다.
확인 부탁합니다.

실행 : python3 main.py

에러 
![image](https://github.com/wonch01/data_to_db/assets/4180063/27b3053d-21dc-47f2-bf18-781a3b12840d)

**Comment by wonch01** [comment]
죄송합니다 json 파일에 오타가 나서 고쳤습니다ㅜ

**Comment by wonch01** [comment]
파일 수정했습니다

**Comment by jeonghoonkang** [comment]
동작확인했습니다.

![image](https://github.com/wonch01/data_to_db/assets/4180063/d01d1225-7588-47f1-be02-f3e4f60de579)
