### ISSUE TITLE
insert_data(conn, cur) 에서 데이터 부분 분리

### ISSUE THREAD

**Issue by jeonghoonkang** [wonch01/data_to_db#3]
insert_data(conn, cur) 에서 데이터 부분 분리하여,

따로 파일을 만드는게 좋을것 같습니다.

데이터 read, 전처리, DB 입력 가능 형식으로 처리 하는 기능은 따로 파일을 만들어서 정리하고,

insert_data(conn, cur) 함수에서는,
insert 할때, 간결하게 보이도록 하는게 좋겠습니다.

DB insert할때는 SQL 문법을 몰라도, 주석을 보면서 SQL 구문을 이해할수 있도록,
주석을 많이 추가해 주면 좋겠습니다.

**Comment by wonch01** [comment]
코드 업데이트, 파일 분리, data_handler.py
